### ISSUE TITLE
Debug task 5.3

### ISSUE THREAD

**Issue by ored95** [Impervguin/Computational-algorithms#1]
Ошибка в опредении коэффициентов СЛАУ (первая и последняя строка возможна).
@Impervguin Посмотрите 2 функции: [`jacobian(*y)` и `f(n)`](https://github.com/Impervguin/Computational-algorithms/blob/main/Task5/Main.ipynb)

Результат работы должен быть таким образом:
|`N`|`y[-2]`|_Ваш результат_|
|:---:|:---:|:---:|
|10|2.46895720610051|_2.46_|
|100|2.9362033420575115|_2.98_|

**Comment by Impervguin** [comment]
Произошло недопонисание, y - вектор значений начального приближения функции. Найденный методом ньютона хранится в переменной res, где значения совпадает с требуемыми:

| N   | y[-2] | res[-2]            | 
|-----|-------|--------------------|
| 10  | 2.8   | 2.46895720610051   |
| 100 | 2.98  | 2.9362033420575115 | 

Для удобства добавил вывод res[-2] и y[-2] в юпитер

**Comment by ored95** [comment]
Работа принята.
